const fs = require("fs");
const PDFDocument = require("pdfkit");

const doc = new PDFDocument({ margin: 50 });
doc.pipe(fs.createWriteStream("Gold_Empire_ROI_Plans.pdf"));

// Title
doc.fontSize(24).fillColor("#D4AF37").text("Gold Empire Investment", { align: "center" });
doc.moveDown();
doc.fontSize(16).fillColor("#158A5E").text("ROI Return Analysis by Stage", { align: "center" });
doc.moveDown(2);

// Description
doc
  .fontSize(12)
  .fillColor("#667085")
  .text(
    "The following is a detailed breakdown of the Return on Investment (ROI) for each stage within the Gold Empire Investment ecosystem. Each plan operates on a standard 30-day duration cycle with daily automatic credits.",
    { align: "left" },
  );
doc.moveDown(2);

const plans = [
  { name: "Silver", min: "$10", max: "$49", roi: "3.0%", duration: "30 Days", total: "90.0%" },
  { name: "Ruby", min: "$50", max: "$499", roi: "5.0%", duration: "30 Days", total: "150.0%" },
  { name: "Gold", min: "$500", max: "$4,999", roi: "8.0%", duration: "30 Days", total: "240.0%" },
  {
    name: "Platinum",
    min: "$5,000",
    max: "$49,999",
    roi: "12.0%",
    duration: "30 Days",
    total: "360.0%",
  },
  {
    name: "Emerald",
    min: "$50,000",
    max: "$199,999",
    roi: "16.0%",
    duration: "30 Days",
    total: "480.0%",
  },
  {
    name: "Diamond",
    min: "$200,000",
    max: "$1,000,000",
    roi: "20.0%",
    duration: "30 Days",
    total: "600.0%",
  },
];

plans.forEach((plan) => {
  doc.fontSize(18).fillColor("#158A5E").text(`${plan.name} Stage`);
  doc
    .fontSize(12)
    .fillColor("#667085")
    .text(`Investment Range: ${plan.min} - ${plan.max}`)
    .text(`Daily ROI: ${plan.roi}`)
    .text(`Duration: ${plan.duration}`)
    .fillColor("#D4AF37")
    .text(`Total Expected ROI: ${plan.total}`)
    .moveDown();
});

// Footer
doc
  .fontSize(10)
  .fillColor("#aaaaaa")
  .text("Generated by Gold Empire Inv System", 50, 700, { align: "center", lineBreak: false });

doc.end();
console.log("PDF created successfully as Gold_Empire_ROI_Plans.pdf");
